#! /bin/sh

xrandr --output DP-0 --primary --mode 1920x1080 --rate 144.00 --rotate normal --output DVI-D-0 --mode 1920x1080 --rotate normal --right-of DP-0
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap hu &
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
~/.fehbg
dunst &
$HOME/.config/polybar/launch.sh &

bspc monitor DP-0 -d 1 2 3 4 5

bspc config border_width            2
bspc config window_gap              7
bspc config top_padding             2

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc rule -a Lxappearance desktop='^5' follow=on
bspc rule -a Pavucontrol desktop='^5' follow=on
bspc rule -a Thunar desktop='^5' follow=on
bspc rule -a Nitrogen desktop='^5' follow=on
bspc rule -a Qbittorrent desktop ='^5' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a code-oss desktop='^3' follow=on
bspc rule -a kitty desktop='^1' follow=on state=floating rectangle=700x400+600+300
bspc rule -a discord desktop='^4'